// resources/js/pages/Admin/TeamMembers/Form.vue
<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue';
import { Head, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({
    teamMember: {
        type: Object,
        default: () => ({
            name: '',
            position: '',
            order: 0,
            image: null,
            image_url: null
        })
    },
    isEdit: {
        type: Boolean,
        default: false
    }
});

const form = useForm({
    name: props.teamMember.name,
    position: props.teamMember.position,
    order: props.teamMember.order,
    image: null
});

const imagePreview = ref(props.teamMember.image_url);

const handleImageChange = (event) => {
    const file = event.target.files[0];
    if (file) {
        form.image = file;
        const reader = new FileReader();
        reader.onload = (e) => {
            imagePreview.value = e.target.result;
        };
        reader.readAsDataURL(file);
    }
};

const submit = () => {
    if (props.isEdit) {
        form.put(route('admin.team-members.update', props.teamMember.id));
    } else {
        form.post(route('admin.team-members.store'));
    }
};
</script>

<template>
    <Head :title="isEdit ? 'Edit Team Member' : 'Create Team Member'" />

    <AdminLayout>
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
                {{ isEdit ? 'Edit Team Member' : 'Create Team Member' }}
            </h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900 dark:text-gray-100">
                        <form @submit.prevent="submit" class="space-y-6">
                            <div>
                                <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                    Name
                                </label>
                                <input
                                    type="text"
                                    id="name"
                                    v-model="form.name"
                                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                                    required
                                />
                                <div v-if="form.errors.name" class="text-red-500 text-sm mt-1">
                                    {{ form.errors.name }}
                                </div>
                            </div>

                            <div>
                                <label for="position" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                    Position
                                </label>
                                <input
                                    type="text"
                                    id="position"
                                    v-model="form.position"
                                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                                    required
                                />
                                <div v-if="form.errors.position" class="text-red-500 text-sm mt-1">
                                    {{ form.errors.position }}
                                </div>
                            </div>

                            <div>
                                <label for="order" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                    Order
                                </label>
                                <input
                                    type="number"
                                    id="order"
                                    v-model="form.order"
                                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                                    required
                                />
                                <div v-if="form.errors.order" class="text-red-500 text-sm mt-1">
                                    {{ form.errors.order }}
                                </div>
                            </div>

                            <div>
                                <label for="image" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                                    Image
                                </label>
                                <input
                                    type="file"
                                    id="image"
                                    @change="handleImageChange"
                                    accept="image/*"
                                    class="mt-1 block w-full text-sm text-gray-500 dark:text-gray-400
                                        file:mr-4 file:py-2 file:px-4
                                        file:rounded-md file:border-0
                                        file:text-sm file:font-semibold
                                        file:bg-indigo-50 file:text-indigo-700
                                        hover:file:bg-indigo-100
                                        dark:file:bg-indigo-900 dark:file:text-indigo-300"
                                />
                                <div v-if="form.errors.image" class="text-red-500 text-sm mt-1">
                                    {{ form.errors.image }}
                                </div>
                                <div v-if="imagePreview" class="mt-2">
                                    <img
                                        :src="imagePreview"
                                        alt="Preview"
                                        class="h-32 w-32 object-cover rounded-lg"
                                    />
                                </div>
                            </div>

                            <div class="flex items-center justify-end">
                                <button
                                    type="submit"
                                    class="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
                                    :disabled="form.processing"
                                >
                                    {{ isEdit ? 'Update' : 'Create' }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AdminLayout>
</template>

// resources/js/pages/News/Form.tsx
import React from 'react';
import { useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

interface NewsItem {
    id?: number;
    title: string;
    content: string;
    featured_image: string | null;
    meta_description: string | null;
    is_published: boolean;
}

interface Props {
    news?: NewsItem;
}

const NewsForm: React.FC<Props> = ({ news }) => {
    const { data, setData, post, put, processing, errors } = useForm({
        title: news?.title || '',
        content: news?.content || '',
        featured_image: null as File | null,
        meta_description: news?.meta_description || '',
        is_published: news?.is_published || false,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (news?.id) {
            put(route('news.update', news.id));
        } else {
            post(route('admin.news.store'));
        }
    };

    return (
        <div className="container mx-auto px-4 py-8">
            <Card className="max-w-4xl mx-auto">
                <CardHeader>
                    <CardTitle className="text-2xl text-[#1e4785]">
                        {news?.id ? 'Edit News' : 'Create News'}
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <form onSubmit={handleSubmit} className="space-y-6">
                        <div className="space-y-2">
                            <Label htmlFor="title">Title</Label>
                            <Input
                                id="title"
                                value={data.title}
                                onChange={(e) => setData('title', e.target.value)}
                                className={errors.title ? 'border-red-500' : ''}
                            />
                            {errors.title && (
                                <p className="text-sm text-red-500">{errors.title}</p>
                            )}
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="content">Content</Label>
                            <Textarea
                                id="content"
                                value={data.content}
                                onChange={(e) => setData('content', e.target.value)}
                                className={errors.content ? 'border-red-500' : ''}
                                rows={10}
                            />
                            {errors.content && (
                                <p className="text-sm text-red-500">{errors.content}</p>
                            )}
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="featured_image">Featured Image</Label>
                            <Input
                                id="featured_image"
                                type="file"
                                onChange={(e) => setData('featured_image', e.target.files?.[0] || null)}
                                className={errors.featured_image ? 'border-red-500' : ''}
                            />
                            {errors.featured_image && (
                                <p className="text-sm text-red-500">{errors.featured_image}</p>
                            )}
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="meta_description">Meta Description</Label>
                            <Textarea
                                id="meta_description"
                                value={data.meta_description}
                                onChange={(e) => setData('meta_description', e.target.value)}
                                className={errors.meta_description ? 'border-red-500' : ''}
                                rows={3}
                            />
                            {errors.meta_description && (
                                <p className="text-sm text-red-500">{errors.meta_description}</p>
                            )}
                        </div>

                        <div className="flex items-center space-x-2">
                            <Switch
                                id="is_published"
                                checked={data.is_published}
                                onCheckedChange={(checked) => setData('is_published', checked)}
                            />
                            <Label htmlFor="is_published">Publish immediately</Label>
                        </div>

                        <div className="flex justify-end space-x-4">
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => window.history.back()}
                            >
                                Cancel
                            </Button>
                            <Button
                                type="submit"
                                className="bg-[#1e4785] hover:bg-[#1e4785]/90"
                                disabled={processing}
                            >
                                {news?.id ? 'Update' : 'Create'} News
                            </Button>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    );
};

export default NewsForm;
